<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-01-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='languages',
            field=models.CharField(choices=[('zh', '中文'), ('ja', '日语'), ('en', '英语'), ('zh_ja', '中文和日语'), ('zh_en', '中文和英语'), ('ja_en', '日语和英语'), ('all', '中文、日语和英语')], default='zh', max_length=10, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='driver',
            name='preferred_vehicle_types',
            field=models.CharField(choices=[('economy', '经济型'), ('business', '商务型'), ('luxury', '豪华型'), ('all', '全部类型')], default='all', max_length=10, verbose_name='擅长车型'),
        ),
    ]
=======
# Generated by Django 5.1.5 on 2025-01-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='languages',
            field=models.CharField(choices=[('zh', '中文'), ('ja', '日语'), ('en', '英语'), ('zh_ja', '中文和日语'), ('zh_en', '中文和英语'), ('ja_en', '日语和英语'), ('all', '中文、日语和英语')], default='zh', max_length=10, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='driver',
            name='preferred_vehicle_types',
            field=models.CharField(choices=[('economy', '经济型'), ('business', '商务型'), ('luxury', '豪华型'), ('all', '全部类型')], default='all', max_length=10, verbose_name='擅长车型'),
        ),
    ]
>>>>>>> 29e35e4892c15854585299d3eee6ff215d96cbb2
