# Generated by Django 5.1.5 on 2025-01-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_review_options_review_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('economy', '经济型'), ('business', '商务型'), ('luxury', '豪华型')], max_length=20, verbose_name='车型')),
                ('time_period', models.CharField(choices=[('normal', '平时'), ('peak', '高峰时段'), ('night', '夜间'), ('holiday', '节假日')], max_length=20, verbose_name='时段')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='起步价')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每公里费用')),
                ('min_distance', models.IntegerField(default=3, verbose_name='最小里程(公里)')),
                ('waiting_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='等待费用(每分钟)')),
                ('night_service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='夜间服务费')),
                ('holiday_markup', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='节假日加价率')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '价格规则',
                'verbose_name_plural': '价格规则',
                'unique_together': {('vehicle_type', 'time_period')},
            },
        ),
    ]
